# Site settings
title: Code Coverage
tagline: 'Niels van Hoorn on Code, the Universe and Everything'
sidebar_image: /images/cover.jpg
email: blog@nvh.io
permalink: /:year/:month/:day/:title.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.nvh.io" # the base hostname & protocol for your site
twitter_username: nvh
github_username:  nvh

# Build settings
markdown: KramdownPygments

kramdown:
  input: GFM
  default_lang: swift
