# Site settings
title: Code Coverage
email: blog@nvh.io
description: > # this means to ignore newlines until "baseurl:"
  Niels van Hoorn on Code, the Universe and Everything
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.nvh.io" # the base hostname & protocol for your site
twitter_username: nvh
github_username:  nvh

# Build settings
markdown: kramdown
